package main

import "fmt"

func main() {
	src := "你好，Go！"
	dst := reverse([]rune(src))
	fmt.Printf("%v\n", string(dst))
	fmt.Println(len(dst))
}

func reverse(s []rune) []rune {
	// 循环将第一个和最后一个进行调换，其它index下的value类似操作
	for i, j := 0, len(s)-1; i < j; i, j = i+1, j-1 {
		s[i], s[j] = s[j], s[i]
	}
	return s
}

/*
内存泄漏分析：

go run  --gcflags=-m reverse_str.go
# command-line-arguments
./reverse_str.go:8:12: inlining call to fmt.Printf
./reverse_str.go:9:13: inlining call to fmt.Println
./reverse_str.go:15:14: reverse ignoring self-assignment in s[i], s[j] = s[j], s[i]
./reverse_str.go:15:14: reverse ignoring self-assignment in s[i], s[j] = s[j], s[i]
./reverse_str.go:12:14: leaking param: s to result ~r1 level=0
./reverse_str.go:7:23: main ([]rune)(src) does not escape
./reverse_str.go:8:27: string(dst) escapes to heap
./reverse_str.go:8:27: string(dst) escapes to heap
./reverse_str.go:8:12: main []interface {} literal does not escape
./reverse_str.go:8:12: io.Writer(os.Stdout) escapes to heap
./reverse_str.go:9:17: len(dst) escapes to heap
./reverse_str.go:9:13: main []interface {} literal does not escape
./reverse_str.go:9:13: io.Writer(os.Stdout) escapes to heap
<autogenerated>:1: (*File).close .this does not escape

*/